/*
Drip Cloud Functions

Drip auxilary backend.

API version: 1.0.0
Contact: team@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dripextension

import (
	"bytes"
	"context"
	"io/ioutil"
	"net/http"
	"net/url"
)


type DefaultApi interface {

	/*
	V1OrcawhirlpoolQuote Get whirlpool swap quote.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiV1OrcawhirlpoolQuoteRequest
	*/
	V1OrcawhirlpoolQuote(ctx context.Context) ApiV1OrcawhirlpoolQuoteRequest

	// V1OrcawhirlpoolQuoteExecute executes the request
	//  @return V1OrcawhirlpoolQuote200Response
	V1OrcawhirlpoolQuoteExecute(r ApiV1OrcawhirlpoolQuoteRequest) (*V1OrcawhirlpoolQuote200Response, *http.Response, error)
}

// DefaultApiService DefaultApi service
type DefaultApiService service

type ApiV1OrcawhirlpoolQuoteRequest struct {
	ctx context.Context
	ApiService DefaultApi
	v1OrcawhirlpoolQuoteRequest *V1OrcawhirlpoolQuoteRequest
}

func (r ApiV1OrcawhirlpoolQuoteRequest) V1OrcawhirlpoolQuoteRequest(v1OrcawhirlpoolQuoteRequest V1OrcawhirlpoolQuoteRequest) ApiV1OrcawhirlpoolQuoteRequest {
	r.v1OrcawhirlpoolQuoteRequest = &v1OrcawhirlpoolQuoteRequest
	return r
}

func (r ApiV1OrcawhirlpoolQuoteRequest) Execute() (*V1OrcawhirlpoolQuote200Response, *http.Response, error) {
	return r.ApiService.V1OrcawhirlpoolQuoteExecute(r)
}

/*
V1OrcawhirlpoolQuote Get whirlpool swap quote.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiV1OrcawhirlpoolQuoteRequest
*/
func (a *DefaultApiService) V1OrcawhirlpoolQuote(ctx context.Context) ApiV1OrcawhirlpoolQuoteRequest {
	return ApiV1OrcawhirlpoolQuoteRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return V1OrcawhirlpoolQuote200Response
func (a *DefaultApiService) V1OrcawhirlpoolQuoteExecute(r ApiV1OrcawhirlpoolQuoteRequest) (*V1OrcawhirlpoolQuote200Response, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *V1OrcawhirlpoolQuote200Response
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "DefaultApiService.V1OrcawhirlpoolQuote")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/orcawhirlpool/quote"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.v1OrcawhirlpoolQuoteRequest == nil {
		return localVarReturnValue, nil, reportError("v1OrcawhirlpoolQuoteRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.v1OrcawhirlpoolQuoteRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v string
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
