/*
Drip Backend

Testing AdminApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package drip

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_drip_AdminApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test AdminApiService V1AdminPositionsGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AdminApi.V1AdminPositionsGet(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AdminApiService V1AdminSummaryActivewalletsGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AdminApi.V1AdminSummaryActivewalletsGet(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AdminApiService V1AdminVaultPubkeyPathEnablePut", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var pubkeyPath string

        resp, httpRes, err := apiClient.AdminApi.V1AdminVaultPubkeyPathEnablePut(context.Background(), pubkeyPath).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AdminApiService V1AdminVaultsGet", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.AdminApi.V1AdminVaultsGet(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
