/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ActiveWallet
 */
export interface ActiveWallet {
    /**
     * 
     * @type {string}
     * @memberof ActiveWallet
     */
    owner: string;
    /**
     * 
     * @type {number}
     * @memberof ActiveWallet
     */
    positionCount: number;
}

/**
 * Check if a given object implements the ActiveWallet interface.
 */
export function instanceOfActiveWallet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "owner" in value;
    isInstance = isInstance && "positionCount" in value;

    return isInstance;
}

export function ActiveWalletFromJSON(json: any): ActiveWallet {
    return ActiveWalletFromJSONTyped(json, false);
}

export function ActiveWalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActiveWallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'owner': json['owner'],
        'positionCount': json['positionCount'],
    };
}

export function ActiveWalletToJSON(value?: ActiveWallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'owner': value.owner,
        'positionCount': value.positionCount,
    };
}

