/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentTVLResponse
 */
export interface CurrentTVLResponse {
    /**
     * A float 64 string for the current tvl in USD.
     * @type {string}
     * @memberof CurrentTVLResponse
     */
    totalUsdValue: string;
}

/**
 * Check if a given object implements the CurrentTVLResponse interface.
 */
export function instanceOfCurrentTVLResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "totalUsdValue" in value;

    return isInstance;
}

export function CurrentTVLResponseFromJSON(json: any): CurrentTVLResponse {
    return CurrentTVLResponseFromJSONTyped(json, false);
}

export function CurrentTVLResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTVLResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalUsdValue': json['totalUsdValue'],
    };
}

export function CurrentTVLResponseToJSON(value?: CurrentTVLResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'totalUsdValue': value.totalUsdValue,
    };
}

