/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProtoConfig,
    ProtoConfigFromJSON,
    ProtoConfigFromJSONTyped,
    ProtoConfigToJSON,
} from './ProtoConfig';
import {
    Token,
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './Token';
import {
    TokenAccount,
    TokenAccountFromJSON,
    TokenAccountFromJSONTyped,
    TokenAccountToJSON,
} from './TokenAccount';

/**
 * 
 * @export
 * @interface ExpandedAdminVaultAllOf
 */
export interface ExpandedAdminVaultAllOf {
    /**
     * 
     * @type {ProtoConfig}
     * @memberof ExpandedAdminVaultAllOf
     */
    protoConfigValue?: ProtoConfig;
    /**
     * 
     * @type {Token}
     * @memberof ExpandedAdminVaultAllOf
     */
    tokenAMintValue?: Token;
    /**
     * 
     * @type {Token}
     * @memberof ExpandedAdminVaultAllOf
     */
    tokenBMintValue?: Token;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVaultAllOf
     */
    tokenAAccountValue?: TokenAccount;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVaultAllOf
     */
    tokenBAccountValue?: TokenAccount;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVaultAllOf
     */
    treasuryTokenBAccountValue?: TokenAccount;
}

export function ExpandedAdminVaultAllOfFromJSON(json: any): ExpandedAdminVaultAllOf {
    return ExpandedAdminVaultAllOfFromJSONTyped(json, false);
}

export function ExpandedAdminVaultAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandedAdminVaultAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'protoConfigValue': !exists(json, 'protoConfigValue') ? undefined : ProtoConfigFromJSON(json['protoConfigValue']),
        'tokenAMintValue': !exists(json, 'tokenAMintValue') ? undefined : TokenFromJSON(json['tokenAMintValue']),
        'tokenBMintValue': !exists(json, 'tokenBMintValue') ? undefined : TokenFromJSON(json['tokenBMintValue']),
        'tokenAAccountValue': !exists(json, 'tokenAAccountValue') ? undefined : TokenAccountFromJSON(json['tokenAAccountValue']),
        'tokenBAccountValue': !exists(json, 'tokenBAccountValue') ? undefined : TokenAccountFromJSON(json['tokenBAccountValue']),
        'treasuryTokenBAccountValue': !exists(json, 'treasuryTokenBAccountValue') ? undefined : TokenAccountFromJSON(json['treasuryTokenBAccountValue']),
    };
}

export function ExpandedAdminVaultAllOfToJSON(value?: ExpandedAdminVaultAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'protoConfigValue': ProtoConfigToJSON(value.protoConfigValue),
        'tokenAMintValue': TokenToJSON(value.tokenAMintValue),
        'tokenBMintValue': TokenToJSON(value.tokenBMintValue),
        'tokenAAccountValue': TokenAccountToJSON(value.tokenAAccountValue),
        'tokenBAccountValue': TokenAccountToJSON(value.tokenBAccountValue),
        'treasuryTokenBAccountValue': TokenAccountToJSON(value.treasuryTokenBAccountValue),
    };
}

