/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProtoConfig } from './ProtoConfig';
import {
    ProtoConfigFromJSON,
    ProtoConfigFromJSONTyped,
    ProtoConfigToJSON,
} from './ProtoConfig';
import type { Token } from './Token';
import {
    TokenFromJSON,
    TokenFromJSONTyped,
    TokenToJSON,
} from './Token';
import type { TokenAccount } from './TokenAccount';
import {
    TokenAccountFromJSON,
    TokenAccountFromJSONTyped,
    TokenAccountToJSON,
} from './TokenAccount';

/**
 * Internal vault schema.
 * @export
 * @interface ExpandedAdminVault
 */
export interface ExpandedAdminVault {
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    pubkey: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    protoConfig: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    tokenAAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    tokenBAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    treasuryTokenBAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    tokenAMint: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    tokenBMint: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    lastDcaPeriod: string;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    dripAmount: string;
    /**
     * unix timestamp
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    dcaActivationTimestamp: string;
    /**
     * 
     * @type {boolean}
     * @memberof ExpandedAdminVault
     */
    enabled: boolean;
    /**
     * 
     * @type {number}
     * @memberof ExpandedAdminVault
     */
    maxSlippageBps: number;
    /**
     * 
     * @type {number}
     * @memberof ExpandedAdminVault
     */
    maxPriceDeviationBps: number;
    /**
     * 
     * @type {string}
     * @memberof ExpandedAdminVault
     */
    oracleConfig?: string;
    /**
     * 
     * @type {ProtoConfig}
     * @memberof ExpandedAdminVault
     */
    protoConfigValue?: ProtoConfig;
    /**
     * 
     * @type {Token}
     * @memberof ExpandedAdminVault
     */
    tokenAMintValue?: Token;
    /**
     * 
     * @type {Token}
     * @memberof ExpandedAdminVault
     */
    tokenBMintValue?: Token;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVault
     */
    tokenAAccountValue?: TokenAccount;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVault
     */
    tokenBAccountValue?: TokenAccount;
    /**
     * 
     * @type {TokenAccount}
     * @memberof ExpandedAdminVault
     */
    treasuryTokenBAccountValue?: TokenAccount;
}

/**
 * Check if a given object implements the ExpandedAdminVault interface.
 */
export function instanceOfExpandedAdminVault(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "pubkey" in value;
    isInstance = isInstance && "protoConfig" in value;
    isInstance = isInstance && "tokenAAccount" in value;
    isInstance = isInstance && "tokenBAccount" in value;
    isInstance = isInstance && "treasuryTokenBAccount" in value;
    isInstance = isInstance && "tokenAMint" in value;
    isInstance = isInstance && "tokenBMint" in value;
    isInstance = isInstance && "lastDcaPeriod" in value;
    isInstance = isInstance && "dripAmount" in value;
    isInstance = isInstance && "dcaActivationTimestamp" in value;
    isInstance = isInstance && "enabled" in value;
    isInstance = isInstance && "maxSlippageBps" in value;
    isInstance = isInstance && "maxPriceDeviationBps" in value;

    return isInstance;
}

export function ExpandedAdminVaultFromJSON(json: any): ExpandedAdminVault {
    return ExpandedAdminVaultFromJSONTyped(json, false);
}

export function ExpandedAdminVaultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpandedAdminVault {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubkey': json['pubkey'],
        'protoConfig': json['protoConfig'],
        'tokenAAccount': json['tokenAAccount'],
        'tokenBAccount': json['tokenBAccount'],
        'treasuryTokenBAccount': json['treasuryTokenBAccount'],
        'tokenAMint': json['tokenAMint'],
        'tokenBMint': json['tokenBMint'],
        'lastDcaPeriod': json['lastDcaPeriod'],
        'dripAmount': json['dripAmount'],
        'dcaActivationTimestamp': json['dcaActivationTimestamp'],
        'enabled': json['enabled'],
        'maxSlippageBps': json['maxSlippageBps'],
        'maxPriceDeviationBps': json['maxPriceDeviationBps'],
        'oracleConfig': !exists(json, 'oracleConfig') ? undefined : json['oracleConfig'],
        'protoConfigValue': !exists(json, 'protoConfigValue') ? undefined : ProtoConfigFromJSON(json['protoConfigValue']),
        'tokenAMintValue': !exists(json, 'tokenAMintValue') ? undefined : TokenFromJSON(json['tokenAMintValue']),
        'tokenBMintValue': !exists(json, 'tokenBMintValue') ? undefined : TokenFromJSON(json['tokenBMintValue']),
        'tokenAAccountValue': !exists(json, 'tokenAAccountValue') ? undefined : TokenAccountFromJSON(json['tokenAAccountValue']),
        'tokenBAccountValue': !exists(json, 'tokenBAccountValue') ? undefined : TokenAccountFromJSON(json['tokenBAccountValue']),
        'treasuryTokenBAccountValue': !exists(json, 'treasuryTokenBAccountValue') ? undefined : TokenAccountFromJSON(json['treasuryTokenBAccountValue']),
    };
}

export function ExpandedAdminVaultToJSON(value?: ExpandedAdminVault | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pubkey': value.pubkey,
        'protoConfig': value.protoConfig,
        'tokenAAccount': value.tokenAAccount,
        'tokenBAccount': value.tokenBAccount,
        'treasuryTokenBAccount': value.treasuryTokenBAccount,
        'tokenAMint': value.tokenAMint,
        'tokenBMint': value.tokenBMint,
        'lastDcaPeriod': value.lastDcaPeriod,
        'dripAmount': value.dripAmount,
        'dcaActivationTimestamp': value.dcaActivationTimestamp,
        'enabled': value.enabled,
        'maxSlippageBps': value.maxSlippageBps,
        'maxPriceDeviationBps': value.maxPriceDeviationBps,
        'oracleConfig': value.oracleConfig,
        'protoConfigValue': ProtoConfigToJSON(value.protoConfigValue),
        'tokenAMintValue': TokenToJSON(value.tokenAMintValue),
        'tokenBMintValue': TokenToJSON(value.tokenBMintValue),
        'tokenAAccountValue': TokenAccountToJSON(value.tokenAAccountValue),
        'tokenBAccountValue': TokenAccountToJSON(value.tokenBAccountValue),
        'treasuryTokenBAccountValue': TokenAccountToJSON(value.treasuryTokenBAccountValue),
    };
}

