/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcafmocha@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListPositionsInner
 */
export interface ListPositionsInner {
    /**
     * 
     * @type {string}
     * @memberof ListPositionsInner
     */
    pubkey: string;
    /**
     * 
     * @type {string}
     * @memberof ListPositionsInner
     */
    vault: string;
    /**
     * 
     * @type {string}
     * @memberof ListPositionsInner
     */
    authority: string;
    /**
     * 
     * @type {number}
     * @memberof ListPositionsInner
     */
    depositedTokenAAmount: number;
    /**
     * 
     * @type {number}
     * @memberof ListPositionsInner
     */
    withdrawnTokenBAmount: number;
    /**
     * 
     * @type {string}
     * @memberof ListPositionsInner
     */
    depositTimestamp: string;
    /**
     * 
     * @type {number}
     * @memberof ListPositionsInner
     */
    dcaPeriodIdBeforeDeposit: number;
    /**
     * 
     * @type {number}
     * @memberof ListPositionsInner
     */
    numberOfSwaps: number;
    /**
     * 
     * @type {number}
     * @memberof ListPositionsInner
     */
    periodicDripAmount: number;
    /**
     * 
     * @type {boolean}
     * @memberof ListPositionsInner
     */
    isClosed: boolean;
}

export function ListPositionsInnerFromJSON(json: any): ListPositionsInner {
    return ListPositionsInnerFromJSONTyped(json, false);
}

export function ListPositionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPositionsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubkey': json['pubkey'],
        'vault': json['vault'],
        'authority': json['authority'],
        'depositedTokenAAmount': json['depositedTokenAAmount'],
        'withdrawnTokenBAmount': json['withdrawnTokenBAmount'],
        'depositTimestamp': json['depositTimestamp'],
        'dcaPeriodIdBeforeDeposit': json['dcaPeriodIdBeforeDeposit'],
        'numberOfSwaps': json['numberOfSwaps'],
        'periodicDripAmount': json['periodicDripAmount'],
        'isClosed': json['isClosed'],
    };
}

export function ListPositionsInnerToJSON(value?: ListPositionsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pubkey': value.pubkey,
        'vault': value.vault,
        'authority': value.authority,
        'depositedTokenAAmount': value.depositedTokenAAmount,
        'withdrawnTokenBAmount': value.withdrawnTokenBAmount,
        'depositTimestamp': value.depositTimestamp,
        'dcaPeriodIdBeforeDeposit': value.dcaPeriodIdBeforeDeposit,
        'numberOfSwaps': value.numberOfSwaps,
        'periodicDripAmount': value.periodicDripAmount,
        'isClosed': value.isClosed,
    };
}

