/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcafmocha@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTokenPairsInner
 */
export interface ListTokenPairsInner {
    /**
     * 
     * @type {string}
     * @memberof ListTokenPairsInner
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenPairsInner
     */
    tokenA: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenPairsInner
     */
    tokenB: string;
}

export function ListTokenPairsInnerFromJSON(json: any): ListTokenPairsInner {
    return ListTokenPairsInnerFromJSONTyped(json, false);
}

export function ListTokenPairsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTokenPairsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tokenA': json['tokenA'],
        'tokenB': json['tokenB'],
    };
}

export function ListTokenPairsInnerToJSON(value?: ListTokenPairsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tokenA': value.tokenA,
        'tokenB': value.tokenB,
    };
}

