/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcafmocha@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListVaultsInner
 */
export interface ListVaultsInner {
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    pubkey: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    protoConfig: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    tokenAAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    tokenBAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    treasuryTokenBAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    tokenAMint: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    tokenBMint: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    lastDcaPeriod: string;
    /**
     * 
     * @type {string}
     * @memberof ListVaultsInner
     */
    dripAmount: string;
    /**
     * unix timestamp
     * @type {string}
     * @memberof ListVaultsInner
     */
    dcaActivationTimestamp: string;
}

export function ListVaultsInnerFromJSON(json: any): ListVaultsInner {
    return ListVaultsInnerFromJSONTyped(json, false);
}

export function ListVaultsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListVaultsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubkey': json['pubkey'],
        'protoConfig': json['protoConfig'],
        'tokenAAccount': json['tokenAAccount'],
        'tokenBAccount': json['tokenBAccount'],
        'treasuryTokenBAccount': json['treasuryTokenBAccount'],
        'tokenAMint': json['tokenAMint'],
        'tokenBMint': json['tokenBMint'],
        'lastDcaPeriod': json['lastDcaPeriod'],
        'dripAmount': json['dripAmount'],
        'dcaActivationTimestamp': json['dcaActivationTimestamp'],
    };
}

export function ListVaultsInnerToJSON(value?: ListVaultsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pubkey': value.pubkey,
        'protoConfig': value.protoConfig,
        'tokenAAccount': value.tokenAAccount,
        'tokenBAccount': value.tokenBAccount,
        'treasuryTokenBAccount': value.treasuryTokenBAccount,
        'tokenAMint': value.tokenAMint,
        'tokenBMint': value.tokenBMint,
        'lastDcaPeriod': value.lastDcaPeriod,
        'dripAmount': value.dripAmount,
        'dcaActivationTimestamp': value.dcaActivationTimestamp,
    };
}

