/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: dcafmocha@protonmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListTokenSwapsInner
 */
export interface ListTokenSwapsInner {
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    pubkey: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    mint: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    authority: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    feeAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    tokenAAccount: string;
    /**
     * 
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    tokenBAccount: string;
    /**
     * token pair reference identifier
     * @type {string}
     * @memberof ListTokenSwapsInner
     */
    pair: string;
}

export function ListTokenSwapsInnerFromJSON(json: any): ListTokenSwapsInner {
    return ListTokenSwapsInnerFromJSONTyped(json, false);
}

export function ListTokenSwapsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTokenSwapsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pubkey': json['pubkey'],
        'mint': json['mint'],
        'authority': json['authority'],
        'feeAccount': json['feeAccount'],
        'tokenAAccount': json['tokenAAccount'],
        'tokenBAccount': json['tokenBAccount'],
        'pair': json['pair'],
    };
}

export function ListTokenSwapsInnerToJSON(value?: ListTokenSwapsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pubkey': value.pubkey,
        'mint': value.mint,
        'authority': value.authority,
        'feeAccount': value.feeAccount,
        'tokenAAccount': value.tokenAAccount,
        'tokenBAccount': value.tokenBAccount,
        'pair': value.pair,
    };
}

