/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MintRequest
 */
export interface MintRequest {
    /**
     * 
     * @type {string}
     * @memberof MintRequest
     */
    mint: string;
    /**
     * 
     * @type {string}
     * @memberof MintRequest
     */
    wallet: string;
    /**
     * 
     * @type {string}
     * @memberof MintRequest
     */
    amount: string;
}

export function MintRequestFromJSON(json: any): MintRequest {
    return MintRequestFromJSONTyped(json, false);
}

export function MintRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mint': json['mint'],
        'wallet': json['wallet'],
        'amount': json['amount'],
    };
}

export function MintRequestToJSON(value?: MintRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mint': value.mint,
        'wallet': value.wallet,
        'amount': value.amount,
    };
}

