/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MintResponse
 */
export interface MintResponse {
    /**
     * 
     * @type {string}
     * @memberof MintResponse
     */
    txHash: string;
}

/**
 * Check if a given object implements the MintResponse interface.
 */
export function instanceOfMintResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "txHash" in value;

    return isInstance;
}

export function MintResponseFromJSON(json: any): MintResponse {
    return MintResponseFromJSONTyped(json, false);
}

export function MintResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MintResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'txHash': json['txHash'],
    };
}

export function MintResponseToJSON(value?: MintResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'txHash': value.txHash,
    };
}

