/* tslint:disable */
/* eslint-disable */
/**
 * Drip Backend
 * Drip backend service. All API\'s have a IP rate limit of 10 requests per second. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mocha@dcaf.so
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenPair
 */
export interface TokenPair {
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    tokenA: string;
    /**
     * 
     * @type {string}
     * @memberof TokenPair
     */
    tokenB: string;
}

/**
 * Check if a given object implements the TokenPair interface.
 */
export function instanceOfTokenPair(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "tokenA" in value;
    isInstance = isInstance && "tokenB" in value;

    return isInstance;
}

export function TokenPairFromJSON(json: any): TokenPair {
    return TokenPairFromJSONTyped(json, false);
}

export function TokenPairFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenPair {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tokenA': json['tokenA'],
        'tokenB': json['tokenB'],
    };
}

export function TokenPairToJSON(value?: TokenPair | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'tokenA': value.tokenA,
        'tokenB': value.tokenB,
    };
}

