/*
Drip Backend

Drip backend service. All API's have a IP rate limit of 10 requests per second. 

API version: 1.0.0
Contact: mocha@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ProtoConfig struct for ProtoConfig
type ProtoConfig struct {
	Pubkey string `json:"pubkey"`
	Admin string `json:"admin"`
	Granularity string `json:"granularity"`
	TokenADripTriggerSpread int32 `json:"tokenADripTriggerSpread"`
	TokenBWithdrawalSpread int32 `json:"tokenBWithdrawalSpread"`
	TokenBReferralSpread int32 `json:"tokenBReferralSpread"`
}

// NewProtoConfig instantiates a new ProtoConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProtoConfig(pubkey string, admin string, granularity string, tokenADripTriggerSpread int32, tokenBWithdrawalSpread int32, tokenBReferralSpread int32) *ProtoConfig {
	this := ProtoConfig{}
	this.Pubkey = pubkey
	this.Admin = admin
	this.Granularity = granularity
	this.TokenADripTriggerSpread = tokenADripTriggerSpread
	this.TokenBWithdrawalSpread = tokenBWithdrawalSpread
	this.TokenBReferralSpread = tokenBReferralSpread
	return &this
}

// NewProtoConfigWithDefaults instantiates a new ProtoConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProtoConfigWithDefaults() *ProtoConfig {
	this := ProtoConfig{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *ProtoConfig) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetPubkeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *ProtoConfig) SetPubkey(v string) {
	o.Pubkey = v
}

// GetAdmin returns the Admin field value
func (o *ProtoConfig) GetAdmin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Admin
}

// GetAdminOk returns a tuple with the Admin field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetAdminOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Admin, true
}

// SetAdmin sets field value
func (o *ProtoConfig) SetAdmin(v string) {
	o.Admin = v
}

// GetGranularity returns the Granularity field value
func (o *ProtoConfig) GetGranularity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Granularity
}

// GetGranularityOk returns a tuple with the Granularity field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetGranularityOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Granularity, true
}

// SetGranularity sets field value
func (o *ProtoConfig) SetGranularity(v string) {
	o.Granularity = v
}

// GetTokenADripTriggerSpread returns the TokenADripTriggerSpread field value
func (o *ProtoConfig) GetTokenADripTriggerSpread() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenADripTriggerSpread
}

// GetTokenADripTriggerSpreadOk returns a tuple with the TokenADripTriggerSpread field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetTokenADripTriggerSpreadOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenADripTriggerSpread, true
}

// SetTokenADripTriggerSpread sets field value
func (o *ProtoConfig) SetTokenADripTriggerSpread(v int32) {
	o.TokenADripTriggerSpread = v
}

// GetTokenBWithdrawalSpread returns the TokenBWithdrawalSpread field value
func (o *ProtoConfig) GetTokenBWithdrawalSpread() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenBWithdrawalSpread
}

// GetTokenBWithdrawalSpreadOk returns a tuple with the TokenBWithdrawalSpread field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetTokenBWithdrawalSpreadOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenBWithdrawalSpread, true
}

// SetTokenBWithdrawalSpread sets field value
func (o *ProtoConfig) SetTokenBWithdrawalSpread(v int32) {
	o.TokenBWithdrawalSpread = v
}

// GetTokenBReferralSpread returns the TokenBReferralSpread field value
func (o *ProtoConfig) GetTokenBReferralSpread() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TokenBReferralSpread
}

// GetTokenBReferralSpreadOk returns a tuple with the TokenBReferralSpread field value
// and a boolean to check if the value has been set.
func (o *ProtoConfig) GetTokenBReferralSpreadOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenBReferralSpread, true
}

// SetTokenBReferralSpread sets field value
func (o *ProtoConfig) SetTokenBReferralSpread(v int32) {
	o.TokenBReferralSpread = v
}

func (o ProtoConfig) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["admin"] = o.Admin
	}
	if true {
		toSerialize["granularity"] = o.Granularity
	}
	if true {
		toSerialize["tokenADripTriggerSpread"] = o.TokenADripTriggerSpread
	}
	if true {
		toSerialize["tokenBWithdrawalSpread"] = o.TokenBWithdrawalSpread
	}
	if true {
		toSerialize["tokenBReferralSpread"] = o.TokenBReferralSpread
	}
	return json.Marshal(toSerialize)
}

type NullableProtoConfig struct {
	value *ProtoConfig
	isSet bool
}

func (v NullableProtoConfig) Get() *ProtoConfig {
	return v.value
}

func (v *NullableProtoConfig) Set(val *ProtoConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableProtoConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableProtoConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProtoConfig(val *ProtoConfig) *NullableProtoConfig {
	return &NullableProtoConfig{value: val, isSet: true}
}

func (v NullableProtoConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProtoConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


