/*
Drip Backend

Drip backend service. All API's have a IP rate limit of 10 requests per second. 

API version: 1.0.0
Contact: mocha@dcaf.so
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package drip

import (
	"encoding/json"
)

// ExpandedAdminVault Internal vault schema.
type ExpandedAdminVault struct {
	Pubkey string `json:"pubkey"`
	ProtoConfig string `json:"protoConfig"`
	TokenAAccount string `json:"tokenAAccount"`
	TokenBAccount string `json:"tokenBAccount"`
	TreasuryTokenBAccount string `json:"treasuryTokenBAccount"`
	TokenAMint string `json:"tokenAMint"`
	TokenBMint string `json:"tokenBMint"`
	LastDcaPeriod string `json:"lastDcaPeriod"`
	DripAmount string `json:"dripAmount"`
	// unix timestamp
	DcaActivationTimestamp string `json:"dcaActivationTimestamp"`
	Enabled bool `json:"enabled"`
	MaxSlippageBps int32 `json:"maxSlippageBps"`
	MaxPriceDeviationBps int32 `json:"maxPriceDeviationBps"`
	OracleConfig *string `json:"oracleConfig,omitempty"`
	ProtoConfigValue *ProtoConfig `json:"protoConfigValue,omitempty"`
	TokenAMintValue *Token `json:"tokenAMintValue,omitempty"`
	TokenBMintValue *Token `json:"tokenBMintValue,omitempty"`
	TokenAAccountValue *TokenAccount `json:"tokenAAccountValue,omitempty"`
	TokenBAccountValue *TokenAccount `json:"tokenBAccountValue,omitempty"`
	TreasuryTokenBAccountValue *TokenAccount `json:"treasuryTokenBAccountValue,omitempty"`
}

// NewExpandedAdminVault instantiates a new ExpandedAdminVault object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpandedAdminVault(pubkey string, protoConfig string, tokenAAccount string, tokenBAccount string, treasuryTokenBAccount string, tokenAMint string, tokenBMint string, lastDcaPeriod string, dripAmount string, dcaActivationTimestamp string, enabled bool, maxSlippageBps int32, maxPriceDeviationBps int32) *ExpandedAdminVault {
	this := ExpandedAdminVault{}
	this.Pubkey = pubkey
	this.ProtoConfig = protoConfig
	this.TokenAAccount = tokenAAccount
	this.TokenBAccount = tokenBAccount
	this.TreasuryTokenBAccount = treasuryTokenBAccount
	this.TokenAMint = tokenAMint
	this.TokenBMint = tokenBMint
	this.LastDcaPeriod = lastDcaPeriod
	this.DripAmount = dripAmount
	this.DcaActivationTimestamp = dcaActivationTimestamp
	this.Enabled = enabled
	this.MaxSlippageBps = maxSlippageBps
	this.MaxPriceDeviationBps = maxPriceDeviationBps
	return &this
}

// NewExpandedAdminVaultWithDefaults instantiates a new ExpandedAdminVault object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpandedAdminVaultWithDefaults() *ExpandedAdminVault {
	this := ExpandedAdminVault{}
	return &this
}

// GetPubkey returns the Pubkey field value
func (o *ExpandedAdminVault) GetPubkey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pubkey
}

// GetPubkeyOk returns a tuple with the Pubkey field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetPubkeyOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Pubkey, true
}

// SetPubkey sets field value
func (o *ExpandedAdminVault) SetPubkey(v string) {
	o.Pubkey = v
}

// GetProtoConfig returns the ProtoConfig field value
func (o *ExpandedAdminVault) GetProtoConfig() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtoConfig
}

// GetProtoConfigOk returns a tuple with the ProtoConfig field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetProtoConfigOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ProtoConfig, true
}

// SetProtoConfig sets field value
func (o *ExpandedAdminVault) SetProtoConfig(v string) {
	o.ProtoConfig = v
}

// GetTokenAAccount returns the TokenAAccount field value
func (o *ExpandedAdminVault) GetTokenAAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAAccount
}

// GetTokenAAccountOk returns a tuple with the TokenAAccount field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenAAccountOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenAAccount, true
}

// SetTokenAAccount sets field value
func (o *ExpandedAdminVault) SetTokenAAccount(v string) {
	o.TokenAAccount = v
}

// GetTokenBAccount returns the TokenBAccount field value
func (o *ExpandedAdminVault) GetTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBAccount
}

// GetTokenBAccountOk returns a tuple with the TokenBAccount field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenBAccountOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenBAccount, true
}

// SetTokenBAccount sets field value
func (o *ExpandedAdminVault) SetTokenBAccount(v string) {
	o.TokenBAccount = v
}

// GetTreasuryTokenBAccount returns the TreasuryTokenBAccount field value
func (o *ExpandedAdminVault) GetTreasuryTokenBAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TreasuryTokenBAccount
}

// GetTreasuryTokenBAccountOk returns a tuple with the TreasuryTokenBAccount field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTreasuryTokenBAccountOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TreasuryTokenBAccount, true
}

// SetTreasuryTokenBAccount sets field value
func (o *ExpandedAdminVault) SetTreasuryTokenBAccount(v string) {
	o.TreasuryTokenBAccount = v
}

// GetTokenAMint returns the TokenAMint field value
func (o *ExpandedAdminVault) GetTokenAMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenAMint
}

// GetTokenAMintOk returns a tuple with the TokenAMint field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenAMintOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenAMint, true
}

// SetTokenAMint sets field value
func (o *ExpandedAdminVault) SetTokenAMint(v string) {
	o.TokenAMint = v
}

// GetTokenBMint returns the TokenBMint field value
func (o *ExpandedAdminVault) GetTokenBMint() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenBMint
}

// GetTokenBMintOk returns a tuple with the TokenBMint field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenBMintOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenBMint, true
}

// SetTokenBMint sets field value
func (o *ExpandedAdminVault) SetTokenBMint(v string) {
	o.TokenBMint = v
}

// GetLastDcaPeriod returns the LastDcaPeriod field value
func (o *ExpandedAdminVault) GetLastDcaPeriod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastDcaPeriod
}

// GetLastDcaPeriodOk returns a tuple with the LastDcaPeriod field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetLastDcaPeriodOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.LastDcaPeriod, true
}

// SetLastDcaPeriod sets field value
func (o *ExpandedAdminVault) SetLastDcaPeriod(v string) {
	o.LastDcaPeriod = v
}

// GetDripAmount returns the DripAmount field value
func (o *ExpandedAdminVault) GetDripAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DripAmount
}

// GetDripAmountOk returns a tuple with the DripAmount field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetDripAmountOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.DripAmount, true
}

// SetDripAmount sets field value
func (o *ExpandedAdminVault) SetDripAmount(v string) {
	o.DripAmount = v
}

// GetDcaActivationTimestamp returns the DcaActivationTimestamp field value
func (o *ExpandedAdminVault) GetDcaActivationTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DcaActivationTimestamp
}

// GetDcaActivationTimestampOk returns a tuple with the DcaActivationTimestamp field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetDcaActivationTimestampOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.DcaActivationTimestamp, true
}

// SetDcaActivationTimestamp sets field value
func (o *ExpandedAdminVault) SetDcaActivationTimestamp(v string) {
	o.DcaActivationTimestamp = v
}

// GetEnabled returns the Enabled field value
func (o *ExpandedAdminVault) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetEnabledOk() (*bool, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *ExpandedAdminVault) SetEnabled(v bool) {
	o.Enabled = v
}

// GetMaxSlippageBps returns the MaxSlippageBps field value
func (o *ExpandedAdminVault) GetMaxSlippageBps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxSlippageBps
}

// GetMaxSlippageBpsOk returns a tuple with the MaxSlippageBps field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetMaxSlippageBpsOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.MaxSlippageBps, true
}

// SetMaxSlippageBps sets field value
func (o *ExpandedAdminVault) SetMaxSlippageBps(v int32) {
	o.MaxSlippageBps = v
}

// GetMaxPriceDeviationBps returns the MaxPriceDeviationBps field value
func (o *ExpandedAdminVault) GetMaxPriceDeviationBps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxPriceDeviationBps
}

// GetMaxPriceDeviationBpsOk returns a tuple with the MaxPriceDeviationBps field value
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetMaxPriceDeviationBpsOk() (*int32, bool) {
	if o == nil {
    return nil, false
	}
	return &o.MaxPriceDeviationBps, true
}

// SetMaxPriceDeviationBps sets field value
func (o *ExpandedAdminVault) SetMaxPriceDeviationBps(v int32) {
	o.MaxPriceDeviationBps = v
}

// GetOracleConfig returns the OracleConfig field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetOracleConfig() string {
	if o == nil || isNil(o.OracleConfig) {
		var ret string
		return ret
	}
	return *o.OracleConfig
}

// GetOracleConfigOk returns a tuple with the OracleConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetOracleConfigOk() (*string, bool) {
	if o == nil || isNil(o.OracleConfig) {
    return nil, false
	}
	return o.OracleConfig, true
}

// HasOracleConfig returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasOracleConfig() bool {
	if o != nil && !isNil(o.OracleConfig) {
		return true
	}

	return false
}

// SetOracleConfig gets a reference to the given string and assigns it to the OracleConfig field.
func (o *ExpandedAdminVault) SetOracleConfig(v string) {
	o.OracleConfig = &v
}

// GetProtoConfigValue returns the ProtoConfigValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetProtoConfigValue() ProtoConfig {
	if o == nil || isNil(o.ProtoConfigValue) {
		var ret ProtoConfig
		return ret
	}
	return *o.ProtoConfigValue
}

// GetProtoConfigValueOk returns a tuple with the ProtoConfigValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetProtoConfigValueOk() (*ProtoConfig, bool) {
	if o == nil || isNil(o.ProtoConfigValue) {
    return nil, false
	}
	return o.ProtoConfigValue, true
}

// HasProtoConfigValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasProtoConfigValue() bool {
	if o != nil && !isNil(o.ProtoConfigValue) {
		return true
	}

	return false
}

// SetProtoConfigValue gets a reference to the given ProtoConfig and assigns it to the ProtoConfigValue field.
func (o *ExpandedAdminVault) SetProtoConfigValue(v ProtoConfig) {
	o.ProtoConfigValue = &v
}

// GetTokenAMintValue returns the TokenAMintValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetTokenAMintValue() Token {
	if o == nil || isNil(o.TokenAMintValue) {
		var ret Token
		return ret
	}
	return *o.TokenAMintValue
}

// GetTokenAMintValueOk returns a tuple with the TokenAMintValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenAMintValueOk() (*Token, bool) {
	if o == nil || isNil(o.TokenAMintValue) {
    return nil, false
	}
	return o.TokenAMintValue, true
}

// HasTokenAMintValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasTokenAMintValue() bool {
	if o != nil && !isNil(o.TokenAMintValue) {
		return true
	}

	return false
}

// SetTokenAMintValue gets a reference to the given Token and assigns it to the TokenAMintValue field.
func (o *ExpandedAdminVault) SetTokenAMintValue(v Token) {
	o.TokenAMintValue = &v
}

// GetTokenBMintValue returns the TokenBMintValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetTokenBMintValue() Token {
	if o == nil || isNil(o.TokenBMintValue) {
		var ret Token
		return ret
	}
	return *o.TokenBMintValue
}

// GetTokenBMintValueOk returns a tuple with the TokenBMintValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenBMintValueOk() (*Token, bool) {
	if o == nil || isNil(o.TokenBMintValue) {
    return nil, false
	}
	return o.TokenBMintValue, true
}

// HasTokenBMintValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasTokenBMintValue() bool {
	if o != nil && !isNil(o.TokenBMintValue) {
		return true
	}

	return false
}

// SetTokenBMintValue gets a reference to the given Token and assigns it to the TokenBMintValue field.
func (o *ExpandedAdminVault) SetTokenBMintValue(v Token) {
	o.TokenBMintValue = &v
}

// GetTokenAAccountValue returns the TokenAAccountValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetTokenAAccountValue() TokenAccount {
	if o == nil || isNil(o.TokenAAccountValue) {
		var ret TokenAccount
		return ret
	}
	return *o.TokenAAccountValue
}

// GetTokenAAccountValueOk returns a tuple with the TokenAAccountValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenAAccountValueOk() (*TokenAccount, bool) {
	if o == nil || isNil(o.TokenAAccountValue) {
    return nil, false
	}
	return o.TokenAAccountValue, true
}

// HasTokenAAccountValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasTokenAAccountValue() bool {
	if o != nil && !isNil(o.TokenAAccountValue) {
		return true
	}

	return false
}

// SetTokenAAccountValue gets a reference to the given TokenAccount and assigns it to the TokenAAccountValue field.
func (o *ExpandedAdminVault) SetTokenAAccountValue(v TokenAccount) {
	o.TokenAAccountValue = &v
}

// GetTokenBAccountValue returns the TokenBAccountValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetTokenBAccountValue() TokenAccount {
	if o == nil || isNil(o.TokenBAccountValue) {
		var ret TokenAccount
		return ret
	}
	return *o.TokenBAccountValue
}

// GetTokenBAccountValueOk returns a tuple with the TokenBAccountValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTokenBAccountValueOk() (*TokenAccount, bool) {
	if o == nil || isNil(o.TokenBAccountValue) {
    return nil, false
	}
	return o.TokenBAccountValue, true
}

// HasTokenBAccountValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasTokenBAccountValue() bool {
	if o != nil && !isNil(o.TokenBAccountValue) {
		return true
	}

	return false
}

// SetTokenBAccountValue gets a reference to the given TokenAccount and assigns it to the TokenBAccountValue field.
func (o *ExpandedAdminVault) SetTokenBAccountValue(v TokenAccount) {
	o.TokenBAccountValue = &v
}

// GetTreasuryTokenBAccountValue returns the TreasuryTokenBAccountValue field value if set, zero value otherwise.
func (o *ExpandedAdminVault) GetTreasuryTokenBAccountValue() TokenAccount {
	if o == nil || isNil(o.TreasuryTokenBAccountValue) {
		var ret TokenAccount
		return ret
	}
	return *o.TreasuryTokenBAccountValue
}

// GetTreasuryTokenBAccountValueOk returns a tuple with the TreasuryTokenBAccountValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpandedAdminVault) GetTreasuryTokenBAccountValueOk() (*TokenAccount, bool) {
	if o == nil || isNil(o.TreasuryTokenBAccountValue) {
    return nil, false
	}
	return o.TreasuryTokenBAccountValue, true
}

// HasTreasuryTokenBAccountValue returns a boolean if a field has been set.
func (o *ExpandedAdminVault) HasTreasuryTokenBAccountValue() bool {
	if o != nil && !isNil(o.TreasuryTokenBAccountValue) {
		return true
	}

	return false
}

// SetTreasuryTokenBAccountValue gets a reference to the given TokenAccount and assigns it to the TreasuryTokenBAccountValue field.
func (o *ExpandedAdminVault) SetTreasuryTokenBAccountValue(v TokenAccount) {
	o.TreasuryTokenBAccountValue = &v
}

func (o ExpandedAdminVault) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["pubkey"] = o.Pubkey
	}
	if true {
		toSerialize["protoConfig"] = o.ProtoConfig
	}
	if true {
		toSerialize["tokenAAccount"] = o.TokenAAccount
	}
	if true {
		toSerialize["tokenBAccount"] = o.TokenBAccount
	}
	if true {
		toSerialize["treasuryTokenBAccount"] = o.TreasuryTokenBAccount
	}
	if true {
		toSerialize["tokenAMint"] = o.TokenAMint
	}
	if true {
		toSerialize["tokenBMint"] = o.TokenBMint
	}
	if true {
		toSerialize["lastDcaPeriod"] = o.LastDcaPeriod
	}
	if true {
		toSerialize["dripAmount"] = o.DripAmount
	}
	if true {
		toSerialize["dcaActivationTimestamp"] = o.DcaActivationTimestamp
	}
	if true {
		toSerialize["enabled"] = o.Enabled
	}
	if true {
		toSerialize["maxSlippageBps"] = o.MaxSlippageBps
	}
	if true {
		toSerialize["maxPriceDeviationBps"] = o.MaxPriceDeviationBps
	}
	if !isNil(o.OracleConfig) {
		toSerialize["oracleConfig"] = o.OracleConfig
	}
	if !isNil(o.ProtoConfigValue) {
		toSerialize["protoConfigValue"] = o.ProtoConfigValue
	}
	if !isNil(o.TokenAMintValue) {
		toSerialize["tokenAMintValue"] = o.TokenAMintValue
	}
	if !isNil(o.TokenBMintValue) {
		toSerialize["tokenBMintValue"] = o.TokenBMintValue
	}
	if !isNil(o.TokenAAccountValue) {
		toSerialize["tokenAAccountValue"] = o.TokenAAccountValue
	}
	if !isNil(o.TokenBAccountValue) {
		toSerialize["tokenBAccountValue"] = o.TokenBAccountValue
	}
	if !isNil(o.TreasuryTokenBAccountValue) {
		toSerialize["treasuryTokenBAccountValue"] = o.TreasuryTokenBAccountValue
	}
	return json.Marshal(toSerialize)
}

type NullableExpandedAdminVault struct {
	value *ExpandedAdminVault
	isSet bool
}

func (v NullableExpandedAdminVault) Get() *ExpandedAdminVault {
	return v.value
}

func (v *NullableExpandedAdminVault) Set(val *ExpandedAdminVault) {
	v.value = val
	v.isSet = true
}

func (v NullableExpandedAdminVault) IsSet() bool {
	return v.isSet
}

func (v *NullableExpandedAdminVault) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpandedAdminVault(val *ExpandedAdminVault) *NullableExpandedAdminVault {
	return &NullableExpandedAdminVault{value: val, isSet: true}
}

func (v NullableExpandedAdminVault) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpandedAdminVault) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


